version: '3.8'
services:
    java-maven-app:
      image: "nanajanashia/demo-app:${TAG}"
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
